#!/bin/sh
# debian/postrm file for r-cran packages
# Copyright 2004, 2005 by Dirk Eddelbuettel <edd@debian.org>

set -e

#DEBHELPER#

case "$1" in
    upgrade|remove|purge)
	if test -x /usr/bin/R; then
	    /usr/bin/R CMD perl /usr/lib/R/share/perl/build-help.pl --htmllists
	fi
        ;;
    failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        ;;
esac


exit 0

